# Generated by Django 3.2.13 on 2022-07-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tourneys', '0002_bgmi_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgmi',
            name='link',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
